version: '3.8'
services:
  app:
    build: Dockerfile.web
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: passwd
    volumes:
      - .:/home/dev/rails-docker-template
    init: true
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
volumes:
  mysql_data:
