version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - 3000:3000
      - 8081:8081
    depends_on:
      - db
      - redis
      - chrome
    environment:
      TZ: Asia/Tokyo
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: passwd
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/home/dev/rails-docker-template
    init: true
    stdin_open: true
    tty: true
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    ports:
      - 3307:3307
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
volumes:
  mysql_data:
  redis_data:
