name: RSpec
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: passwd
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
          - 3307:3307
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    container:
      image: ruby:3
      env:
        RAILS_ENV: test
        TZ: Asia/Tokyo
        DATABASE_HOST: mysql
        DATABASE_USER: root
        DATABASE_PASSWORD: passwd
    steps:
      - uses: actions/checkout@v2
      - name: Gems Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ env.cache-name }}
            ${{ runner.os }}-gem-
            ${{ runner.os }}-
      - name: Setup Bundler
        run: bundle config set path vendor/bundle
      - name: Install Gems
        run: bundle install --jobs 4
      - name: DB Setup
        run: bin/rails db:setup
      - name: Run RSpec
        run: bin/rspec spec
