name: RSpec
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: passwd
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
         - 6379:6379
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    env:
      RAILS_ENV: test
      TZ: Asia/Tokyo
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root
      DATABASE_PASSWORD: passwd
      REDIS_URL: redis://127.0.0.1:6379
      CHROME_HOST: 127.0.0.1
      CHROME_PORT: 4444
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Node Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup Bundler
        run: bundle config set path vendor/bundle
      - name: Install Gems
        run: bundle install --jobs 4
      - name: Install node modules
        run: npm ci
      - name: Build Assets
        run: npm run build
      - name: DB Setup
        env:
          DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: bin/rails db:setup
      - name: Run RSpec
        env:
          DATABASE_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: bin/rspec spec
