name: RSpec
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: bitnami/mysql:8.0.26
        env:
          MYSQL_ROOT_PASSWORD: passwd
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3307:3307
      redis:
        image: redis:6
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    container:
      image: ruby:3
      env:
        RAILS_ENV: test
        TZ: Asia/Tokyo
        DATABASE_HOST: mysql
        DATABASE_USER: root
        DATABASE_PASSWORD: passwd
        REDIS_URL: redis://redis:6379
    steps:
      - uses: actions/checkout@v2
      - name: Gems Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ env.cache-name }}
            ${{ runner.os }}-gem-
            ${{ runner.os }}-
      - name: Node Cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.cache-name }}
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Setup Bundler
        run: bundle config set path vendor/bundle
      - name: Install Gems
        run: bundle install --jobs 4
      - name: Setup Node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
          apt-get update -qq && apt-get install -y --no-install-recommends nodejs
      - name: Install node modules
        run: npm i
      - name: Build Assets
        run: npm run build
      - name: DB Setup
        run: bin/rails db:setup
      - name: Run RSpec
        run: bin/rspec spec
