name: Rubocop
on:
  - push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: passwd
      REDIS_URL: redis://redis:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      - name: Setup Bundler
        run: bundle config set path vendor/bundle
      - name: Install Gems
        run: bundle install --jobs 4
      - name: Run Rubocop
        run: bin/rubocop
